// Generated by Dagger (https://dagger.dev).
package com.hasyolu.readcampus.di;

import com.hasyolu.ktReader.persistence.AppDataBase;
import com.hasyolu.ktReader.persistence.ReadRecordDao;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PersistenceModule_ProvideReadRecordDaoFactory implements Factory<ReadRecordDao> {
  private final Provider<AppDataBase> appDataBaseProvider;

  public PersistenceModule_ProvideReadRecordDaoFactory(Provider<AppDataBase> appDataBaseProvider) {
    this.appDataBaseProvider = appDataBaseProvider;
  }

  @Override
  public ReadRecordDao get() {
    return provideReadRecordDao(appDataBaseProvider.get());
  }

  public static PersistenceModule_ProvideReadRecordDaoFactory create(
      Provider<AppDataBase> appDataBaseProvider) {
    return new PersistenceModule_ProvideReadRecordDaoFactory(appDataBaseProvider);
  }

  public static ReadRecordDao provideReadRecordDao(AppDataBase appDataBase) {
    return Preconditions.checkNotNullFromProvides(PersistenceModule.INSTANCE.provideReadRecordDao(appDataBase));
  }
}
