// Generated by Dagger (https://dagger.dev).
package com.hasyolu.readcampus.di;

import com.hasyolu.ktReader.persistence.AppDataBase;
import com.hasyolu.ktReader.persistence.BookDao;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PersistenceModule_ProvideBookDaoFactory implements Factory<BookDao> {
  private final Provider<AppDataBase> appDataBaseProvider;

  public PersistenceModule_ProvideBookDaoFactory(Provider<AppDataBase> appDataBaseProvider) {
    this.appDataBaseProvider = appDataBaseProvider;
  }

  @Override
  public BookDao get() {
    return provideBookDao(appDataBaseProvider.get());
  }

  public static PersistenceModule_ProvideBookDaoFactory create(
      Provider<AppDataBase> appDataBaseProvider) {
    return new PersistenceModule_ProvideBookDaoFactory(appDataBaseProvider);
  }

  public static BookDao provideBookDao(AppDataBase appDataBase) {
    return Preconditions.checkNotNullFromProvides(PersistenceModule.INSTANCE.provideBookDao(appDataBase));
  }
}
